[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "cyclozarin"
name = "LazerWeaponry"
description = "A Content Warning mod that allows rescue hook to shoot lazer projectiles and adds a PvP mode to play with your friends!"
websiteUrl = "https://github.com/cyclozarin/LazerWeaponry"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Hamunii-AutoHookGenPatcher = "1.0.2"
RugbugRedfern-MyceliumNetworking = "1.0.14"
CommanderCat101-ContentSettings = "1.2.2"
Notest-ConfigSync = "2.0.0"
JustMeForNow-MortalEnemies = "1.1.1"

[build]
icon = "icon.png"
readme = "../../README.md"
outdir = "../dist"

[[build.copy]]
source = "../bin/Release/netstandard2.1/cyclozarin.contentwarning.LazerWeaponry.dll"
target = "/BepInEx/plugins/LazerWeaponry/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE.txt"
target = "/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "mods", "bepinex" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
